### ISSUE TITLE
Decode json errors

### ISSUE THREAD

**Issue by lachie83** [mhausenblas/kboom#5]
I'm occasionally getting spurious json decode errors when trying to run larger numbers of pods.

```
kubectl kboom generate --mode=scale:60 --load=pods:1000
```

```kubectl kboom results
<snip>
2019/04/27 04:10:35 Can't create pod scale-sleeper-936: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-1176: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-767: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-275: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-896: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-160: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-376: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-130: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-921: decode error status 429: decode json: invalid character 'T' looking for beginning of value
2019/04/27 04:10:35 Can't create pod scale-sleeper-403: decode error status 429: decode json: invalid character 'T' looking for beginning of value
<snip>
```

**Comment by mhausenblas** [comment]
Thanks a lot for reporting this @lachie83, much appreciated! 

A quick look at the responsible [code segment](https://github.com/mhausenblas/kboom/blob/1c8e67e20a6fffbd5f6143a8fcca073715e55ef7/pods.go#L44) suggests that I'm overloading the API server with requests, hence the HTTP [429](https://httpstatuses.com/429) response code and due to that, rather than sending JSON back the API server sends some error message in plain-text that the [library](https://github.com/ericchiang/k8s/) tries to decode because it thinks it's actually JSON.

This is not super surprising since I don't have any rate limiting in the [code creation part](https://github.com/mhausenblas/kboom/blob/1c8e67e20a6fffbd5f6143a8fcca073715e55ef7/pods.go#L55-L63). My hunch (or working hypothesis, if you prefer): adding some short, random delays in the `ms` range after `go pr.launch()` should address this issue.

**Comment by lachie83** [comment]
This sounds like a reasonable approach. Just out of interest would it be better to make the go routine handle a 429 from api server?

**Comment by mhausenblas** [comment]
Yeah, handling 429 from API server, in addition, wouldn't hurt. Nevertheless, not hammering the API server like a berserker would prolly not be a bad thing to do, in the first place ;)

**Comment by mhausenblas** [comment]
Or, even better, three scale testing strategies: `berserker` (the current implementation), `good-citizen` (rate limiting), and `graceful` (handling `429`s). WDYT?

**Comment by lachie83** [comment]
I agree but it's probably quickest to implement the `good-citizen` based on your original proposal and ship it.

**Comment by johscheuer** [comment]
@lachie83 are you working on this? We also see this issue in our test setup (and would like to fix it).

**Comment by mhausenblas** [comment]
Thanks for the reminder, will try to put a fix together for this over the weekend

**Comment by mhausenblas** [comment]
@johscheuer given your overall contributions, I mean, if you wanna fix that as well … :)

**Comment by johscheuer** [comment]
I can take a look next week :)

**Comment by mhausenblas** [comment]
OK, super @johscheuer … let's see who's faster, LOL ;)
